### ISSUE TITLE
Users endpoint returns last created account instead of searching based on query.

### ISSUE THREAD

**Issue by kenneaal** [FuelRats/api.fuelrats.com#81] opened 2016-02-28 23:22 UTC
What the subject says.

**Comment by xlexi** [comment] 2016-02-29 13:34
I am unable to reproduce this issue, I suspect it is caused by an index error in elasticsearch. I believe purging the database would be the simplest solution. Would this interfere with your current beta testing?

**Comment by kenneaal** [comment] 2016-02-29 16:25
They'd have to re-register accounts, but that's entirely expected during a test configuration. I'll pull and do tests later tonight.

**Comment by xlexi** [comment] 2016-02-29 16:29
Are you making these operations through HTTP or websocket? if the latter I'd like to see the syntax of your request

**Comment by kenneaal** [comment] 2016-02-29 16:34
The requests are made through WS.
			APIQuery login = new APIQuery();
			login.action = "users:read";
			login.data = new Dictionary<string, string>();
			login.data.Add("email", Properties.Settings.Default.APIUsername);
                        SendQuery(login);

For my test user, it serializes as this:
2016-02-29 00:19:03,489 [21] DEBUG RatTracker_WPF.APIWorker - Sent an APIQuery serialized as: {"action":"users:read","data":{"email":"kenneaal@gmail.com"}}

**Comment by xlexi** [comment] 2016-02-29 16:36
Yeah, that should work. Must be elasticsearch then

**Comment by xlexi** [comment] 2016-03-04 18:35
Resolved in 5761449e5dce2e3c48f5c3b9224d392263a00fd5

**Closed by xlexi** 2016-03-04 18:35 UTC
Labels: bug
