### ISSUE TITLE
Mecha !assign name resolution logic and API support

### ISSUE THREAD

**Issue by dewiniaid** [FuelRats/api.fuelrats.com#106] opened 2016-03-18 04:32 UTC
Here's the current logic process I'm considering for how Mecha will resolve a name in `!assign` to an actual rat.  Some of this will require API support (see #104 and #105, among other things), so I'm mentioning it here.  Feedback would also be useful.

There's a few strategies here: 

- **Nickname search**:
  1. Search for a user with the given nickname.  Continue to next strategy if not found.
  2. Determine the user's default rat for the case's platform.

     | Default Rat Platforms | Unknown case platform    | PC Case   | XB Case   |
     |-----------------------|--------------------------|-----------|-----------| 
     | PC Only               | Assign PC, set platform  | Assign PC | Error     |
     | XB Only               | Assign XB, set platform  | Error     | Assign XB |
     | PC+XB                 | Assign PC, leave platform unknown | Assign PC | Assign XB |
     The *error*s here mean Mecha yells at the dispatcher and rat to pay attention to the case.

     Whenever a case's platform is changed, Mecha will look up any rats associated with the wrong platform.  If they have a default rat of the correct platform, the 'wrong' rat is unassigned and the default rat of the correct platform is assigned.  This essentially mimics the process that would have happened if the platform was set prior to assignment like it should be

- **CMDRname search**
  1. Search for rat(s) with the given CMDR name.
  2. Assign them using similar logic as nickname seaches, except: If one of the "Error" cases trigger and the rat's user has a default rat with the correct platform, choose that rat instead.

The search process then is to try the following, in order, until a lookup succeeds.  Any search that would be an exact repeat of a previous step is skipped.

1. If *name* is an exact match of a nickname Mecha currently knows about, attempt a nickname search using *name*.  
2. If *name* is an exact match of a nickname Mecha currently knows about and Mecha knows who that nickname is identified as, nickname search using the account name.
3. Attempt a CMDRname search using *name*.
4. If neither of steps 1&2 have triggered, attempt a nickname search using *name*.  (This may seem redundant, but it means a CMDR match takes priority over a nickname match unless tab-completion was used.)
5. Create *reduced*, which is a stripped-down version of *name*, by selecting the first condition that passes:
  - If *name* contains `[` in the first character and also contains a `]`, set *reduced* to everything after the `]`.  (This reduces `[TAG]name` to `name`)
  - If *name* contains `[` or `|` anywhere other than the first character, set *reduced* to everything before the first of those two characters.
6. Attempt CMDRname search using *reduced*, if present
7. Attempt nickname search using *reduced*, if present
8. Assign fails.

Here's where API support can be useful:

1. Implementing #104 and #105.
2. People using underscores in place of spaces and other invalid-on-IRC characters is fairly common.  If there was a way to have a way to do a CMDRname search that followed similar semantics, it'd help.
3. As an alternative or in addition to 2, having a 'normalized name' attribute consisting of: CMDRname, lowercased, with all characters not matching `[a-z0-9]` removed to search against.
4. Levenshtein distance would probably be overkill.  If implemented at all, it'd be most useful against 3.
5. A one-shot lookup function that implements some of this logic in one request would be useful.  It could accept a payload of the form `{ "name": "Name on !assign", "is_nickname": true_if_is_exact_match, "account": "irc account name, null if unknown", "platform": "case's platform or unknown" }` and get back either nothing or one or more rats.  (Multiple rats is possible if the normalized name or wildcard matching is implemented.)  In the case of platform mismatch errors, it should return the mismatching rat rather than an error -- Mecha can detect the mismatch on its end and will have more to go on.

**Comment by xlexi** [comment] 2016-03-18 07:11
THis is a duplicate of #55 for organisation purposes I am closing the previous thread all further discussion on the topic should continue here

**Comment by xlexi** [comment] 2016-03-18 07:25
#104 and #105 have been accepted and will be implemented as soon as I have the chance.   
     
On the other issue: I do not see the point of this, it would add a lot of unneeded work and complexity to an API way behind schedule, and it's really not that difficult for people to stick to their usual nicknames when they are going to do rescues.     
    
I will however note that the API already implements Levenstein distance based search on any field in the rescues:read and rats:read endpoints, however if nicknames are moved to users this will not be possible as users are not search indexed for security reasons.

**Comment by dewiniaid** [comment] 2016-03-18 16:40
as far as #55 being closed goes: There were a few things that it pointed out that ended up wrong:

Mecha (nor manual API calls I've tried) have ever been able to appropriately assign by CMDR name/IRC name, at least not last time I checked.  That's not important though: Mecha already needs the logic to look up rats by ID to fully resolve details on a rescue.  (This being unless there is/will be an API option to include all of the related rats by more than just their API.  JSONAPI even has a [provision](http://jsonapi.org/format/#document-resource-object-relationships) for this.)  

Also, the 'user' field is not visible on `/api/rats/:id` -- but that's not critical since one can call `/api/users/?CMDRs=id` to get the user anyways.  (It means I can't use a cache of users as effectively, but that just means slightly higher API load.).

re: Levenshtein distance: It's not important for nicknames since they should be an exact match regardless.  (Ignoring the tag-cutting that can happen in step 5.)  It's more useful for CMDR names, which should still be on the rat model and thus fine.  Out of curiosity, what happens if two rats have equal distance from a search?

**Comment by xlexi** [comment] 2016-03-20 11:50
There is no user field on the rat, it's a one-to-many relationships in mongodb does not automatically add a relation on the recipient, because mongo is weird.     
      
It returns an array of the closest matches, the distance is retunred in a 'score' field

**Closed** 2016-05-24 12:22 UTC
Labels: discusson
